---
- name: Ensure the .ssh directory exists in the user's home
  file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory
    mode: '0700'
- name: Ensure the SSH private key is set up
  copy:
    src: '{{ role_path }}/files/id_ed25519'
    dest: '{{ ansible_env.HOME}}/.ssh/id_ed25519'
    mode: '0600'
    decrypt: true
- name: Start ssh-agent and add key.
  shell: |
    eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519
  changed_when: false
