---
- name: Install Zsh
  apt:
    name: zsh
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Change default shell to zsh
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
  become: true
- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
- name: Remove existing dotfiles or directories
  file:
    path: '{{ item.dest }}'
    state: absent
  with_items:
    - {dest: ~/.gitconfig}
    - {dest: ~/.zshrc}
    - {dest: ~/.p10k.zsh}
- name: Create symbolic links for dotfiles
  file:
    src: '{{ role_path }}/files/{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - {src: .gitconfig, dest: ~/.gitconfig}
    - {src: .zshrc, dest: ~/.zshrc}
    - {src: .p10k.zsh, dest: ~/.p10k.zsh}
- name: Install powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: '{{ ansible_env.HOME }}/.local/powerlevel10k'
    depth: 1
- name: Configure powerlevel10k in .zshrc
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    line: source ~/.local/powerlevel10k/powerlevel10k.zsh-theme
    create: true
- name: Ensure main exists
  file:
    path: ~/main
    state: directory
- name: Ensure ~/.local/bin exists
  file:
    path: ~/.local/bin
    state: directory
- name: Set aliases and common paths
  lineinfile:
    path: ~/.zprofile
    line: '{{ item }}'
    create: true
  with_items:
    - alias main="cd ~/main"
    - export PATH=$PATH:~/.local/bin
    - alias ac="source ./bin/activate"
    - alias da="deactivate"
    - "export PATH=$(echo $PATH | tr ':' '\n' | grep -v /mnt/c | tr '\n' ':')"
- name: unbind keys
  lineinfile:
    path: ~/.zprofile
    line: '{{ item }}'
    create: true
  with_items:
    - bindkey '^H' undefined-key
    - bindkey '^J' undefined-key
    - bindkey '^K' undefined-key
    - bindkey '^L' undefined-key
- name: Set aliases and common paths
  lineinfile:
    path: ~/.zshrc
    line: source ~/.zprofile
    create: true
