---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Install base packages
  apt:
    name:
      - git
      - curl
      - fuse
      - libfuse2
      - unzip
      - clangd
      - gcc
      - g++
      - ripgrep
      - ngrep
      - memcached
      - pkg-config
      - libssl-dev
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Disable memcached service
  systemd:
    name: memcached
    state: stopped
    enabled: false
  when: ansible_facts['os_family'] == 'Debian'
