---
- name: Install basic packages
  apt:
    name:
      - git
      - tmux
      - curl
      - fuse
      - libfuse2
      - unzip
      - clangd
      - gcc
      - g++
      - ripgrep
    state: latest
