---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600  # Optional: cache is considered valid for 1 hour to avoid updating it too frequently

- name: Install basic packages
  apt:
    name:
      - git
      - curl
      - fuse
      - libfuse2
      - unzip
      - clangd
      - gcc
      - g++
      - ripgrep
      - python3-pip
      - python3.10-venv
    state: latest

- name: Ensure main exists
  ansible.builtin.file:
    path: ~/main
    state: directory
  become_user: "{{ ansible_user }}"

- name: Set aliases and common paths
  lineinfile:
    path: "~/.zprofile"
    line: "{{ item }}"
    create: yes
  with_items:
    - 'alias main="cd ~/main"'
    - "export PATH=$PATH:~/.local/bin"
    - 'alias ac="source ./bin/activate"'
    - 'alias da="deactivate"'
  become_user: "{{ ansible_user }}"

- name: unbind keys
  lineinfile:
    path: "~/.zprofile"
    line: "{{ item }}"
    create: yes
  with_items:
    - "bindkey '^H' undefined-key"
    - "bindkey '^J' undefined-key"
    - "bindkey '^K' undefined-key"
    - "bindkey '^L' undefined-key"
  become_user: "{{ ansible_user }}"
