---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install basic packages
  apt:
    name:
      - git
      - curl
      - fuse
      - libfuse2
      - unzip
      - clangd
      - gcc
      - g++
      - ripgrep
      - python3-pip
      - python3.10-venv
    state: latest
  become: yes

- name: Ensure main exists
  file:
    path: ~/main
    state: directory
  become_user: "{{ ansible_user }}"

- name: Ensure ~/.local/bin exists
  file:
    path: ~/.local/bin
    state: directory
  become_user: "{{ ansible_user }}"

- name: Set aliases and common paths
  lineinfile:
    path: "~/.zprofile"
    line: "{{ item }}"
    create: yes
  with_items:
    - 'alias main="cd ~/main"'
    - "export PATH=$PATH:~/.local/bin"
    - 'alias ac="source ./bin/activate"'
    - 'alias da="deactivate"'
    - "export PATH=$(echo $PATH | tr ':' '\n' | grep -v /mnt/c | tr '\n' ':')"
  become_user: "{{ ansible_user }}"

- name: unbind keys
  lineinfile:
    path: "~/.zprofile"
    line: "{{ item }}"
    create: yes
  with_items:
    - "bindkey '^H' undefined-key"
    - "bindkey '^J' undefined-key"
    - "bindkey '^K' undefined-key"
    - "bindkey '^L' undefined-key"
  become_user: "{{ ansible_user }}"
