---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600  # Optional: cache is considered valid for 1 hour to avoid updating it too frequently

- name: Install basic packages
  apt:
    name:
      - git
      - curl
      - fuse
      - libfuse2
      - unzip
      - clangd
      - gcc
      - g++
      - ripgrep
      - python3-pip
      - python3.10-venv
    state: latest

- name: Ensure main exists
  ansible.builtin.file:
    path: /home/{{ ssh_user }}/main
    state: directory
  become: no  # Run as the ansible user, not root
  become_user: "{{ ssh_user }}"  # Ensure this task runs as the ssh_user

- name: Set alias to main
  lineinfile:
    path: "/home/{{ ssh_user }}/.zprofile"
    line: "{{ item }}"
    create: yes
  with_items:
    - 'alias main="cd ~/main"'
  become: yes
