---
- name: Download Go tarball
  get_url:
    url: "https://golang.org/dl/go1.22.0.linux-amd64.tar.gz"
    dest: "/tmp/go.tar.gz"
  become: yes

- name: Extract Go tarball
  unarchive:
    src: "/tmp/go.tar.gz"
    dest: "/usr/local"
    creates: "/usr/local/go"
    remote_src: yes
  become: yes

- name: Set Go environment variables in my .profile
  lineinfile:
    path: "/home/{{ ssh_user }}/.zprofile"
    line: "{{ item }}"
    create: yes
  with_items:
    - 'export PATH=$PATH:/usr/local/go/bin'
    - 'export GOPATH=$HOME/go'
  become: yes

- name: Remove Go tarball
  file:
    path: "/tmp/go.tar.gz"
    state: absent
  become: yes
