---
- name: Ensure the .ssh directory exists in the user's home
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
  become_user: "{{ ssh_user }}"

- name: Ensure the SSH private key is set up
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: "~/.ssh/id_ed25519"
    mode: '0600'
  become_user: "{{ ssh_user }}"

