- name: Install Tmux
  package:
    name: tmux
    state: present
  become: yes

- name: Clone TPM (Tmux Plugin Manager)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "~/.tmux/plugins/tpm"
    version: master
  args:
    accept_hostkey: yes
    force: yes
