---
- name: Install python packages
  apt:
    name: [python3.10, python3.10-venv, python3-pip]
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Install ipython using pip
  pip:
    name: ipython
    state: present
    executable: pip3
- name: Install tox using pip
  pip:
    name: tox
    state: present
    executable: pip3
- name: Install mdserve using pip
  pip:
    name: mdserve
    state: present
    executable: pip3
- name: Add readme alias to .zprofile
  lineinfile:
    path: ~/.zprofile
    line: alias readme="mdserve -p 8000"
    create: true
