---
- name: Install Rust
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: ~/.cargo/bin/rustc
- name: Add ~/.cargo/bin to PATH
  ansible.builtin.lineinfile:
    path: ~/.zprofile
    line: export PATH="$HOME/.cargo/bin:$PATH"
    create: true
- name: Add rust-analyzer component
  command: ~/.cargo/bin/rustup component add rust-analyzer
  register: rust_analyzer_result
  changed_when: "'unchanged' not in rust_analyzer_result.stdout"
