---
- name: Check if ~/wezterm directory exists
  stat:
    path: ~/wezterm
  register: wezterm_dir
- name: Download WezTerm source tarball
  get_url:
    url: https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/wezterm-20240203-110809-5046fc22-src.tar.gz
    dest: ~/wezterm-src.tar.gz
  when: not wezterm_dir.stat.exists
- name: Extract WezTerm source
  unarchive:
    src: ~/wezterm-src.tar.gz
    dest: ~/
    remote_src: true
  when: not wezterm_dir.stat.exists
- name: Rename extracted directory to wezterm
  command: mv ~/wezterm-20240203-110809-5046fc22 ~/wezterm
  when: not wezterm_dir.stat.exists
- name: Run get-deps script
  shell: ./get-deps
  args:
    chdir: ~/wezterm
  when: not wezterm_dir.stat.exists
- name: Build WezTerm
  shell: cargo build --release
  args:
    chdir: ~/wezterm
  when: not wezterm_dir.stat.exists
- name: Add WezTerm binary path to .zprofile
  lineinfile:
    path: ~/.zprofile
    line: export PATH="$HOME/wezterm/target/release:$PATH"
    create: true
  when: not wezterm_dir.stat.exists
- name: Create WezTerm .desktop file
  copy:
    dest: ~/.local/share/applications/wezterm.desktop
    content: |
      [Desktop Entry]
      Name=WezTerm
      Comment=A GPU-accelerated cross-platform terminal emulator and multiplexer
      Exec={{ ansible_env.HOME }}wezterm/target/release/wezterm
      Icon=utilities-terminal
      Terminal=false
      Type=Application
      Categories=System;TerminalEmulator;
    mode: '0755'
  when: not wezterm_dir.stat.exists
- name: Clean up WezTerm source tarball
  file:
    path: ~/wezterm-src.tar.gz
    state: absent
  when: not wezterm_dir.stat.exists
- name: Remove existing dotfiles or directories
  file:
    path: ~/.wezterm.lua
    state: absent
- name: Create symbolic links for dotfiles
  file:
    src: '{{ role_path }}/files/.wezterm.lua'
    dest: ~/.wezterm.lua
    state: link
