---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Install base packages
  apt:
    name:
      - git
      - curl
      - unzip
      - gcc
      - g++
      - clangd
      - ripgrep
      - ngrep
      - pkg-config
      - libssl-dev
      - graphviz
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'
