---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Install base packages
  apt:
    name:
      - git
      - curl
      - fuse
      - libfuse2
      - unzip
      - gcc
      - g++
      - ngrep
      - memcached
      - pkg-config
      - libssl-dev
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Install additional packages on the latest versions
  apt:
    name: [clangd, ripgrep]
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian' and ansible_distribution == 'Ubuntu'
    and ansible_distribution_version is version('22.04', '>=')
- name: Disable memcached service
  systemd:
    name: memcached
    state: stopped
    enabled: false
  become: true
  when: ansible_facts['os_family'] == 'Debian'
- name: Install Wezterm on macOS
  ansible.builtin.command:
    cmd: brew install --cask wezterm
  when: ansible_os_family == 'Darwin'
- name: Remove existing dotfiles or directories
  file:
    path: ~/.wezterm.lua
    state: absent
- name: Create symbolic links for dotfiles
  file:
    src: '{{ role_path }}/files/.wezterm.lua'
    dest: ~/.wezterm.lua
    state: link
