[shell]
program = "/usr/bin/zsh"

[cursor]
style = "Beam"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 6

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[env]
TERM="xterm-256color"
