---
- name: Detect architecture and operating system
  command: uname -m
  register: arch_output
- name: Set Go architecture variable
  set_fact:
    go_arch: "{% if 'arm' in arch_output.stdout %}arm64{% elif 'aarch64' in arch_output.stdout\
      \ %} aarch64{% else %}amd64{% endif %}"
    go_os: "{% if ansible_system == 'Linux' %}linux{% else %}darwin{% endif %}"
- name: Download Go binary
  get_url:
    url: https://golang.org/dl/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz
    dest: /tmp/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz
- name: Ensure install dir exists
  file:
    path: '{{ go_install_dir }}'
    state: directory
- name: Extract Go tarball
  command: tar -xvzf /tmp/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz -C
    {{ go_install_dir }}
- name: Remove Go archive
  file:
    path: /tmp/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz
    state: absent
- name: Add Go binary to PATH in .zprofile
  lineinfile:
    path: ~/.zprofile
    line: export PATH=$PATH:{{ go_install_dir }}/go/bin
    create: true
    mode: '0644'
